### ISSUE TITLE
Is the Noir circuit checking for fid < 10000?

### ISSUE THREAD

**Issue by harshnambiar** [33bits-xyz/app#4]
Hi. I was trying to work through the Noir<>Farcaster integration and this repository seemed to have that. I am looking the v2 Noir circuit:
```
fn main(
  fid: Field,
  timestamp: pub u64,
  public_key_preimage: Field,
  public_key: Field,
  // Merkle membership proof
  note_root: pub Field,
  index: Field,
  note_hash_path: [Field; 16],
  // Message
  message: pub [Field; 16],
  // Reply cast id
  reply: pub [Field; 4]
) -> pub ([Field; 16], u64, [Field; 4]) {
  let expected_public_key = std::hash::mimc_bn254([public_key_preimage]);

  assert(expected_public_key == public_key);

  // assert(public_key == expected_public_key);
  let commitment = std::hash::mimc_bn254([fid, public_key]);

  // Check that the input note commitment is in the root
  let new_root = compute_root_from_leaf(commitment, index, note_hash_path);
  assert(new_root == note_root);

  (message, timestamp, reply)
}
```

I'm wondering where the fid < 10000 part is being tested, and what the public_key_preimage comes from. Would appreciate some assistance.

**Comment by pavlovdog** [comment]
Hey @harshnambiar ! Sorry for the long response :) The circuit does not need to check the fid validity, it's done on the API side. What API does is checking the `note_root` - it should be known to the API. And since API calculates the `note_root` out of the FIDs < 10k / 20k / <any other filter>, it automatically means that FIDs > 20k can't prove their presence in that tree.
